### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by HeadReaper-hc** [chenzhike110/Semantic-Motion-Retargeting#3]
Hi,
      Thanks for sharing the code. Do I need to train myself first to use this for inference ?

**Comment by chenzhike110** [comment]
We are sorry. As the project is in collaboration with Huawei and uses their commercial data, the open source for the checkpoints is still in their approval process. We are also waiting for their response. 40G cuda memory is needed if you trained your model with the minimal pretrained checkpoint for BLIP2. And if you want to finetune the vision language model along with the retargeting network, you can use llava instead which has less parameters if you keep vision encoder and language model frozen.
