### ISSUE TITLE
Blender version

### ISSUE THREAD

**Issue by HospitableHost** [chenzhike110/Semantic-Motion-Retargeting#7]
What version of blender are you using? I'm using 4.2. After converting the fbx file to a bvh file, pymo parsing reported an error.

**Comment by HospitableHost** [comment]
The regular expression in the pymo code is incorrect. After I corrected it, there are still some subsequent errors. Can you open source your modified pymo code? Thank you very much！

**Comment by HospitableHost** [comment]
I solved this problem myself.

**Comment by LannnSun** [comment]
> I solved this problem myself.
Excuse me, I would like to ask, does the Blender version have any impact on data processing? And how to get diffuse texture through Blender? I look forward to your reply, thank you very much
